# Generated by Django 3.2.9 on 2021-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
