# Generated by Django 3.2.9 on 2021-11-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='logo_image',
        ),
    ]
