# Generated by Django 3.2.9 on 2021-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211129_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
    ]
