# Generated by Django 3.2.9 on 2021-12-02 15:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('tarjeta_producto', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add your Block Content', required=True)), ('tag1', wagtail.core.blocks.CharBlock(help_text='Tag1', required=True)), ('tag2', wagtail.core.blocks.CharBlock(help_text='Tag2', required=True)), ('tag3', wagtail.core.blocks.CharBlock(help_text='Tag3', required=True))]))], blank=True, null=True),
        ),
    ]
