# Generated by Django 3.2.9 on 2021-12-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_remove_flexpage_productoss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
    ]
