# Generated by Django 3.2.9 on 2021-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_product_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Slug para identificar productos por esta categoría', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product_page',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
    ]
