# Generated by Django 3.2.9 on 2021-12-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20211202_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_page',
            options={'verbose_name': 'Página de Producto', 'verbose_name_plural': 'Páginas de Producto'},
        ),
    ]
