# Generated by Django 3.2.9 on 2021-12-02 23:07

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_product_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_page',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product_page',
            name='content',
            field=wagtail.core.fields.StreamField([('tarjeta_producto', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your Block Content', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('boton_ver_mas', wagtail.core.blocks.PageChooserBlock(required=False)), ('boton_comprar', wagtail.core.blocks.PageChooserBlock(required=False)), ('tag1', wagtail.core.blocks.CharBlock(help_text='Tag1', required=True)), ('tag2', wagtail.core.blocks.CharBlock(help_text='Tag2', required=True)), ('tag3', wagtail.core.blocks.CharBlock(help_text='Tag3', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
