# Generated by Django 3.2.9 on 2021-12-02 23:17

from django.db import migrations
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20211202_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_page',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='product_page',
            name='content',
            field=wagtail.core.fields.StreamField([('tarjeta_producto', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your Block Content', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('boton_ver_mas', wagtail.core.blocks.PageChooserBlock(required=False)), ('boton_comprar', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
