# Generated by Django 3.2.9 on 2021-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20211202_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, help_text='cantidad de unidades disponibles', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='SKU',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
