# Generated by Django 3.2.9 on 2021-12-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20211202_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_producto',
            new_name='categorias_producto',
        ),
    ]
