# Generated by Django 3.2.9 on 2021-12-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
    ]
