# Generated by Django 3.2.9 on 2021-12-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_auto_20211206_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descontado',
            field=models.FloatField(default=15.99),
            preserve_default=False,
        ),
    ]
