# Generated by Django 3.2.9 on 2021-12-02 21:04

from django.db import migrations

def tipos_docs_populate(apps, schema_editor):
    #importo el modelo historico
    tipo_docs_m=apps.get_model('clientes','tipos_docs')
    t1=tipos_docs_m(tipo="C.I")
    t1.save()
    t2=tipos_docs_m(tipo="PASAPORTE")
    t2.save()
    t3=tipos_docs_m(tipo3="OTRO")
    t3.save()
class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
    ]
