# Generated by Django 3.2.9 on 2021-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20211202_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_docs',
            name='tipo1',
        ),
        migrations.RemoveField(
            model_name='tipos_docs',
            name='tipo2',
        ),
        migrations.RemoveField(
            model_name='tipos_docs',
            name='tipo3',
        ),
        migrations.AddField(
            model_name='tipos_docs',
            name='tipo',
            field=models.CharField(default='C.I', max_length=50),
        ),
    ]
