# Generated by Django 3.2.9 on 2021-12-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211202_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_docs',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
